[project]
name = "8-amaliyot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all,standart]>=0.118.0",
    "jinja2>=3.1.6",
    "psutil>=7.1.0",
]
